### ISSUE TITLE
usage confusing need more guide (and also facing many strange bugs?...)

### ISSUE THREAD

**Issue by rightester** [YaAlex3/patcher-oss#1]
I tried to run it on my PC(win10) but failed...

```
C:\Users\rightester\Desktop\temp>py
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
C:\Users\rightester\Desktop\temp>py main.py
  File "main.py", line 18
    Refer to README.md for additional instructions."""
                                                     ^
SyntaxError: invalid syntax

```

So I once tried to delete all the "f" before the string  and it can run but will exit with low version warning

```
C:\Users\rightester\Desktop\temp>py main.py boot.img
ERROR: Python version too old. at least 3.9.0
```
(Oh no this is so weird, I just install the py 3.9.1 for this warning but it's still not working...)(actually 3.7.5 won't raise SyntaxError (?) (maybe it require only 3.9.0?)

Anyway, I annotated(#) that line, added a line "pass", and tried to run it again, and...

```
C:\Users\rightester\Desktop\temp>py main.py boot.img
ERROR: Can't found IMG magic number
```
oh...
the tested two boot.img files are Redmi7A MIUI global version and CN version, so maybe not the version's problem
I have no idea if I have properly settled down the environment

Can any more detailed guide or tutorial be added to this project for more easily getting started ?

I browse this repo because the redirect of the link [patcher.yaalex.tk](url) , thanks for this website I got my Redmi7A rooted. but there are other guys asking for the method to root and stuck on the step packing the boot img...

Sorry for disturbing, thanks for glancing, hope to be replyed soon(

**Comment by YaAlex3** [comment]
1. Open your eyes and read readme. you're supposed to unpack the image with third party tools and use my tool to patch the kernel, then pack your image back
2. Windows support was never advertised. Tested on ubuntu 18.04, 20.04 with python 3.9.1
arch with python 3.9.1
3. if you want - contribute and write a good guide, I can't care less honestly

**Comment by rightester** [comment]
Thank you very much! I'm happy to get your remind, I think I know how to use it. I will try again.
I apologize for not reading the readme more carefully (Sorry but I'm a really new hand and I didn't get the meaning before p_q)
(I will try it on linux environment.)
(sorry for my rudeness)
