### ISSUE TITLE
How to Patch my boot img?

### ISSUE THREAD

**Issue by sfksuperman** [YaAlex3/patcher-oss#14]
Hi,

I am using Redmi 8A (olivelite) device. I want to root my device, for which I need to patch my rom's boot image.

But in a video tutorial shown [here](https://www.youtube.com/watch?v=RKtUIAqhzW8), to patch boot image, we need to use this site and do like that.

But now the [link](http://patcher.yaalex.tk/) is redirecting to this github and I don't have idea how to do that.

Please help.

**Comment by YaAlex3** [comment]
read the instructions in readme. md

**Comment by sfksuperman** [comment]
![Screenshot_20210609-003026__01.jpg](https://user-images.githubusercontent.com/34414624/121242301-03505280-c8ba-11eb-96d0-dfe441e663f5.jpg)

See, I am not a programmer or developer that I understand what you mean by this. So this tutorial is not handy.

What happened to the video tutorial where people patch their boot image online without much hassle? Or atleast make a video how to do it now 

Regards.

**Comment by YaAlex3** [comment]
will you pay me for the video?
a good amount which will pay off my time loss making that?

**Comment by sfksuperman** [comment]
Hi,

Even the money nothing could have been said in a quite pleasant way and I
wouldn't take it as bad.
But the direct statement like this only shows your bad temper and arrogance!

Regards.
